# Generated by Django 3.2.25 on 2024-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choc_category_name', models.CharField(max_length=200)),
                ('choc_friendly_name', models.CharField(blank=True, max_length=200, null=True)),
                ('choc_category_desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Chocolate Categories',
            },
        ),
        migrations.CreateModel(
            name='DietaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_type', models.CharField(max_length=200)),
                ('dietary_description', models.TextField()),
                ('diet_friendly_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dietary Types',
            },
        ),
    ]
