# Generated by Django 3.2.25 on 2024-05-25 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choc_category', models.CharField(max_length=200)),
                ('choc_category_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DietaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_type', models.CharField(max_length=200)),
                ('dietary_description', models.TextField()),
                ('diet_friendly_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choc_name', models.CharField(max_length=200)),
                ('choc_description', models.TextField()),
                ('choc_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('choc_image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('choc_price', models.FloatField()),
                ('choc_ingredients', models.TextField()),
                ('choc_fat', models.FloatField()),
                ('choc_protein', models.FloatField()),
                ('choc_carbs', models.FloatField()),
                ('choc_sugar', models.FloatField()),
                ('choc_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocolates.chocolatecategory')),
                ('choc_dietary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocolates.dietarytype')),
            ],
        ),
    ]
