# Generated by Django 3.2.25 on 2024-05-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chocolatecategory',
            options={'verbose_name_plural': 'Chocolate Categories'},
        ),
    ]
