# Generated by Django 3.2.25 on 2024-05-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choc_name', models.CharField(max_length=200)),
                ('choc_friendly_name', models.CharField(blank=True, max_length=200, null=True)),
                ('choc_description', models.TextField()),
                ('choc_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('choc_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('choc_image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('choc_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('choc_pieces', models.IntegerField(blank=True, null=True)),
                ('choc_ingredients', models.TextField()),
                ('choc_fat', models.FloatField()),
                ('choc_protein', models.FloatField()),
                ('choc_carbs', models.FloatField()),
                ('choc_sugar', models.FloatField()),
                ('choc_category_display', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocolates.chocolatecategory')),
                ('choc_dietary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocolates.dietarytype')),
            ],
        ),
    ]
