# Generated by Django 3.2.25 on 2024-05-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0002_alter_chocolatecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietarytype',
            options={'verbose_name_plural': 'Dietary Types'},
        ),
    ]
