# Generated by Django 3.2.25 on 2024-05-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0002_chocolate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolate',
            name='choc_calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
