# Generated by Django 3.2.25 on 2024-05-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0003_alter_dietarytype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolate',
            name='choc_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
