# Generated by Django 3.2.25 on 2024-05-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0003_chocolate_choc_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolatecategory',
            name='choc_category_dietary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocolates.dietarytype'),
        ),
    ]
