# Generated by Django 3.2.25 on 2024-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0004_chocolatecategory_choc_category_dietary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolatecategory',
            name='choc_category_name',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
    ]
