# Generated by Django 3.2.25 on 2024-05-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0005_chocolate_choc_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolatecategory',
            name='choc_friendly_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
