# Generated by Django 3.2.25 on 2024-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0005_alter_chocolatecategory_choc_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarytype',
            name='dietary_type',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
    ]
