# Generated by Django 3.2.25 on 2024-06-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0006_alter_dietarytype_dietary_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chocolatecategory',
            old_name='choc_friendly_name',
            new_name='choc_category_friendly_name',
        ),
    ]
