# Generated by Django 3.2.25 on 2024-06-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0007_rename_choc_friendly_name_chocolatecategory_choc_category_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='choc_name',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
    ]
