# Generated by Django 3.2.25 on 2024-06-10 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chocolates', '0008_alter_chocolate_choc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choc_rating', models.IntegerField(default=3)),
                ('review_content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('chocolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choc_reviews', to='chocolates.chocolate')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choc_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
