# Generated by Django 3.2.25 on 2024-06-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0009_chocolatereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolatereview',
            name='publish_review',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
