# Generated by Django 3.2.25 on 2024-06-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0011_alter_chocolatereview_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chocolate',
            name='choc_rating',
        ),
    ]
