# Generated by Django 3.2.25 on 2024-06-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0013_chocolate_choc_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='choc_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
