# Generated by Django 3.2.25 on 2024-06-17 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0016_auto_20240617_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='choc_calories',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_carbs',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_category_display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocolates.chocolatecategory'),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_dietary_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocolates.dietarytype'),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_fat',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_name',
            field=models.SlugField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_pieces',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_protein',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='choc_sugar',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
