# Generated by Django 3.2.25 on 2024-06-18 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolates', '0020_auto_20240618_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='choc_calories',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
