# Generated by Django 3.2.25 on 2024-06-09 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_user_display', models.CharField(max_length=50)),
                ('testimonial_text', models.TextField()),
                ('testimonial_date', models.DateField()),
                ('testimonial_publish', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('testimonial_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Testimonials',
            },
        ),
    ]
